language: cpp
dist: xenial
script:
  - which -a python
  - which -a python2
  - which -a python3
  #- python3 --version
  #- python3 -m pip install flake8 || more
  - pyenv install --list
  - pyenv install --force 3.6.3 
  - which -a python3 || true
  - which -a python3.6 || true
  #- pyenv global 3.6.3
  - ls -l $(pyenv root)/versions/3.6.3/
  - $(pyenv root)/versions/3.6.3/bin/python -m pip install flake8
  - $(pyenv root)/versions/3.6.3/bin/python -m flake8 --version
  #- python3 --version
  #- python3 -m pip install --upgrade pip
  #- python3 -m pip install flake8
  #- python3 -m flake8 --version

after_success:
  - sudo apt-get update
  - sudo apt-get install tree
  - echo -e "\`\`\`bash\n$(tree)\n\`\`\`"
