# #!/c/Windows/System32/WindowsPowerShell/v1.0/powershell

os: windows
language: shell
# env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
  - choco install python
  - py --version || true
  - py -c "import sys ; print(sys.executable)"
  - python --version || true
  - grep Python /c/ProgramData/chocolatey/logs/chocolatey.log || true
  - grep Python /c/ProgramData/chocolatey/logs/chocolatey.log | /c/Windows/py make_path_sh.py > temp.sh
  # - /c/Windows/py --version || true
  # - /c/Windows/py make_path_sh.py > temp.sh
  - cat temp.sh
  - echo $PATH
  - source temp.sh
  - echo $PATH
  - which python
  - where python
  - python --version
  - python -m pip install --upgrade pip
  - py --version
  - py --help
script:
  - where powershell || true
  - which powershell || true
  - where py || true         # C:\Windows\py.exe
  - which py || true         # /c/Windows/py
  - where python || true     # C:\Python37\python.exe and C:\ProgramData\chocolatey\bin\python.exe
  - which python || true     # /c/Python37/python
  - where python3 || true    # None!!!
  - which python3 || true    # None!!!
  - where python37 || true  # None!!!
  - which python37 || true  # None!!!
  - where python3.7 || true  # None!!!
  - which python3.7 || true  # None!!!
  - where pip || true        # C:\Python37\Scripts\pip.exe
  - which pip || true        # /c/Python37/Scripts/pip
  - where pip3 || true       # C:\Python37\Scripts\pip3.exe
  - which pip3 || true       # /c/Python37/Scripts/pip3
