language: cpp
# https://docs.travis-ci.com/user/multi-cpu-architectures
# https://docs.travis-ci.com/user/languages/python/#python-versions
arch:
  - amd64
  - arm64
  - aarch64
  - ppc64le
  - s390x
  - x86_64
script:
- ls -la
- python3 --version
- python3 -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo -H python3
- python3 -m pip install --user flake8
- flake8 --version
