language: node_js
node_js:
- 'node'
script:
- python3 --version
- python3 -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo -H python3
- python3 -m pip install --user flake8
- flake8 --version
