language: python
python: 3.9
addons:
  apt:
    packages:
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
      - libgmp-dev 
      - libmpfr-dev
      - libsuitesparse-dev
      - ccache
      - libmpc-dev
install: pip install qiskit-aer
script: true
